apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: intranet-forwarder-server
  name: intranet-forwarder-server
  namespace: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intranet-forwarder-server
  template:
    metadata:
      labels:
        app: intranet-forwarder-server
        buildVersion: build-${BUILD_ID}
    spec:
      containers:
      - command:
        - java
        - '-Xms64m'
        - '-Xmx256m'
        - '-jar'
        - app.jar
        env:
        - name: LANG
          value: C.UTF-8
        - name: JAVA_HOME
          value: /usr/lib/jvm/java-1.8-openjdk
        image: >-
          registry-vpc.cn-shenzhen.aliyuncs.com/registry_tam/intranet-forwarder-server:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        name: intranet-forwarder-server
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: volume-tmp
        - mountPath: /usr/local/app/config
          name: volume-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: volume-tmp
      - configMap:
          defaultMode: 420
          name: intranet-forwarder-server-config
        name: volume-config

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-wz9ja13xj2ta4bwynpian
  name: intranet-forwarder-server-service
  namespace: middleware
spec:
  ports:
  - name: http
    port: 2040
    protocol: TCP
    targetPort: 80
  - name: websocket
    port: 2046
    protocol: TCP
    targetPort: 2046
  selector:
    app: intranet-forwarder-server
  sessionAffinity: None
  type: LoadBalancer
